[general]
import = [
    "C:\\Users\\sterx\\AppData\\Roaming\\alacritty\\themes\\themes\\coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 0.84
startup_mode = "Maximized"

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 12

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "wsl", args = [ "-d", "Debian", "--cd", "~" ] }